export const cintas = [
    {
      id: 1,
      img: "../assets/images/ciron.jpeg",
      title: "Corplus. Iron",
      desc: "Cinta profesional con motor de corriente alterna de 3.8 HP, súper resistente.",
      descLarg: "Cinta profesional en tres versiones, motor de 3.8 HP de corriente alterna, motor de 4.2 de corriente alterna y 4.5 HP de corriente continua. La cinta C#IRON AC+ es un modelo con la última tecnología enfocada en el cuidado de la salud y el cuerpo.",
      price: "$ 592.670",
      stock:"7",
      category: "cintas",
      datos: {
        motor: ["3.8 corriente continua", "4.2 corriente continua", "4.5 corriente alterna"],
        velocidad: ["16 KM/H", "20 KM/H", "24 KM/H"],
      }, 
    },
    {
      id: 2,
      img: "../assets/images/zsmax15.jpeg",
      title: "Zellens Max 15",
      desc: "Cinta motorizada profesional que llega a 24 km/h. Motor de 4.0 HP y pantalla LCD.",
      descLarg: "Cinta profesional en tres versiones, motor de 3.8 HP de corriente alterna, motor de 4.2 de corriente alterna y 4.5 HP de corriente continua. La cinta C#IRON AC+ es un modelo con la última tecnología enfocada en el cuidado de la salud y el cuerpo.",
      price: "$ 656.890",
      stock:"5",
      category: "cintas",
    },
    {
      id: 3,
      img: "../assets/images/gc282.jpeg",
      title: "Fitage GC-282",
      desc: "Cinta profesional con motor profesional y 20 niveles de inclinación automática.",
      descLarg: "Cinta profesional en tres versiones, motor de 3.8 HP de corriente alterna, motor de 4.2 de corriente alterna y 4.5 HP de corriente continua. La cinta C#IRON AC+ es un modelo con la última tecnología enfocada en el cuidado de la salud y el cuerpo.",
      price: "$ 688.920",
      stock:"4",
      category: "cintas",
    },
    {
      id: 4,
      img: "../assets/images/bpower_1.jpeg",
      title: "Corplus. Power",
      desc: "Carrera suave y fluida ideal para un entrenamiento profesional en casa.",
      descLarg: "La Bicicleta indoor Corplus B#Power cuenta con una rueda de inercia de 20 kg y freno por fricción. Ofrece una experiencia de carrera suave y fluida ideal para un entrenamiento profesional. Su computadora mide scan, tiempo, velocidad y distancia.",
      price: "$ 176.990",
      stock:"8",
      category: "indoor",
    },
    {
      id: 5,
      img: "../assets/images/zlspinnen.jpeg",
      title: "Zellens. Spinnen",
      desc: "Máxima calidad estructural, diseño alemán, firme, silenciosa y profesional.",
      descLarg: "Bici Spinning Profesional del más alto nivel tecnológico y estructural. Un modelo exitoso en toda Europa, que llega a la Argentina este 2021. La ZL-Spinnen de Zellens es un diseño alemán que cuenta con un volante liso y silencioso de 20 kg CNC de hierro fundido.",
      price: "$ 186.890",
      stock:"3",
      category: "indoor",
    },
    {
      id: 6,
      img: "../assets/images/90tm.jpeg",
      title: "Omiko. 90TM",
      desc: "Bicicleta Spinning Residencial Omiko 90TM, con un disco de inercia de 22kg.",
      descLarg: "Bicicleta Spinning Residencial Omiko 90TM, un equipo de excelentes prestaciones que tiene un disco de inercia de 22kg con resistencia regulable. Una bici fuerte y sólida que soporta un peso de hasta 130 kg. Asiento antiprostático, ajustable vertical y horizontalmente.",
      price: "$ 198.920",
      stock:"6",
      category: "indoor",
    },
    {
      id: 7,
      img: "../assets/images/53tl.jpeg",
      title: "Omiko. 53TL",
      desc: "El nuevo caminador elíptico Omiko 53TL permite un entrenamiento completo.",
      descLarg: "Caminador elíptico de uso residencial que propone un entrenamiento completo y de fácil aprendizaje. Propone diversas comodidades para el usuario como un asiento ajustable en altura del mismo y una computadora donde se visualiza de forma sencilla el tiempo, velocidad, calorías y distancia.",
      price: "$ 42.990",
      stock:"9",
      category: "elipticos",
    },
    {
      id: 8,
      img: "../assets/images/mlife_1.jpeg",
      title: "Corplus. Life",
      desc: "Corplus Life es un eliptico muy completo, ideal para combinaciones de ejercicios.",
      descLarg: "Caminador elíptico Corplus Life de uso residencial, con rueda de inercia de 7 kg y freno magnético. Manillar móvil y fijo con sensor de pulso, ideal para una combinación de ejercicios en el tronco superior. Su computadora mide scan, tiempo, velocidad, calorías, distancia, pulso, y odómetro.",
      price: "$ 126.150",
      stock:"12",
      category: "elipticos",
    },
    {
      id: 9,
      img: "../assets/images/zn5070_1.jpeg",
      title: "Zellens ZN5070",
      desc: "Caminador elíptico Zellens ZN5070 semiprofesional.",
      descLarg: "Caminador elíptico Zellens ZN 5070 semiprofesional con rueda de inercia de 18 kg y freno magnético, que permite un ejercicio de piernas y abdomen intensivo. Su computadora mide scan, tiempo, velocidad, calorías, distancia y odómetro.",
      price: "$ 288.680",
      stock:"4",
      category: "elipticos",
    },
  ];